In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('train.csv')

In [3]:
df.shape

(404290, 6)

In [4]:
new_df = df.sample(30000)

In [5]:
new_df.isnull().sum()

id              0
qid1            0
qid2            0
question1       0
question2       0
is_duplicate    0
dtype: int64

In [6]:
new_df.duplicated().sum()

np.int64(0)

In [7]:
ques_df = new_df[['question1','question2']]
ques_df.head()

                                                question1                                          question2
263047    How do you know if your guinea pig is pregnant?      How should I care for my pregnant Guinea Pig?
38370                            What is a system theory?          What is the systems theory in management?
333194                              What do SIM cards do?                                What is a SIM card?
252338  What are the reader's views on Harry Potter an...  Did you dislike Harry Potter and the Cursed Ch...
221863                   How do know when you're in love?              How do you know when it is true love?

### Bow

In [8]:
from sklearn.feature_extraction.text import CountVectorizer
# merge texts
questions = list(ques_df['question1']) + list(ques_df['question2'])

cv = CountVectorizer(max_features=3000)
q1_arr, q2_arr = np.vsplit(cv.fit_transform(questions).toarray(),2)

In [9]:
temp_df1 = pd.DataFrame(q1_arr, index = ques_df.index)
temp_df2 = pd.DataFrame(q2_arr, index = ques_df.index)
temp_df = pd.concat([temp_df1,temp_df2],axis=1)
temp_df.shape

(30000, 6000)

In [10]:
temp_df

        0     1     2     3     4     5     ...  2994  2995  2996  2997  2998  2999
263047     0     0     0     0     0     0  ...     0     0     0     0     0     0
38370      0     0     0     0     0     0  ...     0     0     0     0     0     0
333194     0     0     0     0     0     0  ...     0     0     0     0     0     0
252338     0     0     0     0     0     0  ...     0     0     0     0     0     0
221863     0     0     0     0     0     0  ...     0     0     0     0     0     0
...      ...   ...   ...   ...   ...   ...  ...   ...   ...   ...   ...   ...   ...
246523     0     0     0     0     0     0  ...     0     0     0     0     0     0
227167     0     0     0     0     0     0  ...     0     0     0     0     0     0
256057     0     0     0     0     0     0  ...     0     0     0     0     0     0
8345       0     0     0     0     0     0  ...     0     0     0     0     0     0
125626     0     0     0     0     0     0  ...     0     0     0     0     0     0

[30000 rows x 6000 columns]

In [11]:
temp_df['is_duplicate'] = new_df['is_duplicate']

In [12]:
temp_df.head()

        0  1  2  3  4  5  6  ...  2994  2995  2996  2997  2998  2999  is_duplicate
263047  0  0  0  0  0  0  0  ...     0     0     0     0     0     0             0
38370   0  0  0  0  0  0  0  ...     0     0     0     0     0     0             0
333194  0  0  0  0  0  0  0  ...     0     0     0     0     0     0             0
252338  0  0  0  0  0  0  0  ...     0     0     0     0     0     0             1
221863  0  0  0  0  0  0  0  ...     0     0     0     0     0     0             1

[5 rows x 6001 columns]

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(temp_df.iloc[:,0:-1].values,temp_df.iloc[:,-1].values, test_size = 0.2, random_state=1)

In [14]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
rf = RandomForestClassifier()
rf.fit(X_train,y_train)
y_pred = rf.predict(X_test)
accuracy_score(y_test,y_pred)

0.743

In [21]:
from xgboost import XGBClassifier
xgb = XGBClassifier()
xgb.fit(X_train,y_train)
y_pred = xgb.predict(X_test)
accuracy_score(y_test,y_pred)

0.7351666666666666